<?php
// auto-generated by sfPropelCrud
// date: 2008/03/27 01:00:56
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $member->getId() ?></td>
</tr>
<tr>
<th>Member status: </th>
<td><?php echo $member->getMemberStatusId() ?></td>
</tr>
<tr>
<th>Username: </th>
<td><?php echo $member->getUsername() ?></td>
</tr>
<tr>
<th>Password: </th>
<td><?php echo $member->getPassword() ?></td>
</tr>
<tr>
<th>First name: </th>
<td><?php echo $member->getFirstName() ?></td>
</tr>
<tr>
<th>Last name: </th>
<td><?php echo $member->getLastName() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $member->getEmail() ?></td>
</tr>
<tr>
<th>Sex: </th>
<td><?php echo $member->getSex() ?></td>
</tr>
<tr>
<th>Reviewed by: </th>
<td><?php echo $member->getReviewedBy() ?></td>
</tr>
<tr>
<th>Reviewed at: </th>
<td><?php echo $member->getReviewedAt() ?></td>
</tr>
<tr>
<th>Is stared: </th>
<td><?php echo $member->getIsStared() ?></td>
</tr>
<tr>
<th>Current flags: </th>
<td><?php echo $member->getCurrentFlags() ?></td>
</tr>
<tr>
<th>Total flags: </th>
<td><?php echo $member->getTotalFlags() ?></td>
</tr>
<tr>
<th>Unsuspended: </th>
<td><?php echo $member->getUnsuspended() ?></td>
</tr>
<tr>
<th>Country: </th>
<td><?php echo $member->getCountry() ?></td>
</tr>
<tr>
<th>State: </th>
<td><?php echo $member->getState() ?></td>
</tr>
<tr>
<th>District: </th>
<td><?php echo $member->getDistrict() ?></td>
</tr>
<tr>
<th>City: </th>
<td><?php echo $member->getCity() ?></td>
</tr>
<tr>
<th>Zip: </th>
<td><?php echo $member->getZip() ?></td>
</tr>
<tr>
<th>Language: </th>
<td><?php echo $member->getLanguage() ?></td>
</tr>
<tr>
<th>Birthday: </th>
<td><?php echo $member->getBirthday() ?></td>
</tr>
<tr>
<th>Display zodiac sign: </th>
<td><?php echo $member->getDisplayZodiacSign() ?></td>
</tr>
<tr>
<th>Marital status: </th>
<td><?php echo $member->getMaritalStatusId() ?></td>
</tr>
<tr>
<th>Children: </th>
<td><?php echo $member->getChildrenId() ?></td>
</tr>
<tr>
<th>Living situation: </th>
<td><?php echo $member->getLivingSituationId() ?></td>
</tr>
<tr>
<th>Children in future: </th>
<td><?php echo $member->getChildrenInFutureId() ?></td>
</tr>
<tr>
<th>Essay headline: </th>
<td><?php echo $member->getEssayHeadline() ?></td>
</tr>
<tr>
<th>Essay introduction: </th>
<td><?php echo $member->getEssayIntroduction() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $member->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'members/edit?id='.$member->getId()) ?>
&nbsp;<?php echo link_to('list', 'members/list') ?>
