<?php
// auto-generated by sfPropelCrud
// date: 2008/05/07 13:20:11
?>
<?php

/**
 * subscriptions actions.
 *
 * @package    pr
 * @subpackage subscriptions
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class subscriptionsActions extends sfActions
{
  public function executeList()
  {
    $this->subscriptions = SubscriptionPeer::doSelect(new Criteria());
  }

  public function executeEdit()
  {
    //$subscription = SubscriptionPeer::retrieveByPk($this->getRequestParameter('id'));
    //$this->forward404Unless($subscription);
    $subscriptions = SubscriptionPeer::doSelect(new Criteria());
    
    if( $this->getRequest()->getMethod() == sfRequest::POST )
    {
        $this->getUser()->checkPerm(array('subscriptions_edit'));
        $req_subs = $this->getRequestParameter('subs');
        foreach ($subscriptions as $subscription)
        {
            if( array_key_exists($subscription->getId(), $req_subs) )
            {
                $subscription->setCanCreateProfile($req_subs[$subscription->getId()]['can_create_profile']);
                $subscription->setCreateProfiles($req_subs[$subscription->getId()]['create_profiles']);
                $subscription->setCanPostPhoto($req_subs[$subscription->getId()]['can_post_photo']);
                $subscription->setPostPhotos($req_subs[$subscription->getId()]['post_photos']);
                $subscription->setCanWink($req_subs[$subscription->getId()]['can_wink']);
                $subscription->setWinks($req_subs[$subscription->getId()]['winks']);
                $subscription->setWinksDay($req_subs[$subscription->getId()]['winks_day']);
                $subscription->setCanReadMessages($req_subs[$subscription->getId()]['can_read_messages']);
                $subscription->setReadMessages($req_subs[$subscription->getId()]['read_messages']);
                $subscription->setReadMessagesDay($req_subs[$subscription->getId()]['read_messages_day']);
                $subscription->setCanReplyMessages($req_subs[$subscription->getId()]['can_reply_messages']);
                $subscription->setReplyMessages($req_subs[$subscription->getId()]['reply_messages']);
                $subscription->setReplyMessagesDay($req_subs[$subscription->getId()]['reply_messages_day']);
                $subscription->setCanSendMessages($req_subs[$subscription->getId()]['can_send_messages']);
                $subscription->setSendMessages($req_subs[$subscription->getId()]['send_messages']);
                $subscription->setSendMessagesDay($req_subs[$subscription->getId()]['send_messages_day']);
                $subscription->setCanSeeViewed($req_subs[$subscription->getId()]['can_see_viewed']);
                $subscription->setSeeViewed($req_subs[$subscription->getId()]['see_viewed']);
                $subscription->setCanContactAssistant($req_subs[$subscription->getId()]['can_contact_assistant']);
                $subscription->setContactAssistant($req_subs[$subscription->getId()]['contact_assistant']);
                $subscription->setContactAssistantDay($req_subs[$subscription->getId()]['contact_assistant_day']);
                $subscription->setPreApprove(@$req_subs[$subscription->getId()]['pre_approve']);
                
                $subscription->setPeriod($this->getRequestParameter('period'));
                $subscription->setPeriodType($this->getRequestParameter('period_type'));                
                $subscription->setAmount($req_subs[$subscription->getId()]['amount']);
                $subscription->setImbraAmount($req_subs[$subscription->getId()]['imbra_amount']);
                $subscription->save();   
                
                sfSettingPeer::updateFromRequest(array('currency_en', 'currency_pl'));
            }
        }
        
	    return $this->redirect('subscriptions/list');
    }
    
    $this->subscriptions = $subscriptions;
    $this->sub1 = $subscriptions[0];
  }

  public function validateEdit()
  {
    if( $this->getRequest()->getMethod() == sfRequest::POST )
    {                  
        if( !is_numeric($this->getRequestParameter('period')) || $this->getRequestParameter('period') <= 0 )
        {
            $this->getRequest()->setError('period', 'Please enter a positive integer');
            return false;
            
        }
        
        //regular subscription
        switch ($this->getRequestParameter('period_type')) {
            case 'D':
                if( $this->getRequestParameter('period') > 90 )
                {
                    $this->getRequest()->setError('period', 'Allowable range is 1 to 90');
                    return false;
                }
                break;
            case 'W':
                if( $this->getRequestParameter('period') > 52 )
                {
                    $this->getRequest()->setError('period', 'Allowable range is 1 to 52');
                    return false;
                }            
                break;
            case 'M':
                if( $this->getRequestParameter('period') > 24 )
                {
                    $this->getRequest()->setError('period', 'Allowable range is 1 to 24');
                    return false;
                }            
                break;
            case 'Y':
                if( $this->getRequestParameter('period') > 5 )
                {
                    $this->getRequest()->setError('period', 'Allowable range is 1 to 5');
                    return false;
                }            
                break;
            default:
                break;
        }               
    }
    
    return true;
  }
  
  public function handleErrorEdit()
  {
      $subscriptions = SubscriptionPeer::doSelect(new Criteria());
      $this->subscriptions = $subscriptions;
      $this->sub1 = $subscriptions[0];  
      
      return sfView::SUCCESS;    
  }
}
