<?php
// auto-generated by sfPropelCrud
// date: 2008/05/07 13:20:11
?>
<?php

/**
 * subscriptions actions.
 *
 * @package    pr
 * @subpackage subscriptions
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class subscriptionsActions extends sfActions
{
  public function executeList()
  {
    $this->subscriptions = SubscriptionPeer::doSelect(new Criteria());
  }

  public function executeEdit()
  {
    //$subscription = SubscriptionPeer::retrieveByPk($this->getRequestParameter('id'));
    //$this->forward404Unless($subscription);
    $subscriptions = SubscriptionPeer::doSelect(new Criteria());
    
    if( $this->getRequest()->getMethod() == sfRequest::POST )
    {
        $this->getUser()->checkPerm(array('subscriptions_edit'));
        $req_subs = $this->getRequestParameter('subs');
        foreach ($subscriptions as $subscription)
        {
            if( array_key_exists($subscription->getId(), $req_subs) )
            {
                $subscription->setCanCreateProfile($req_subs[$subscription->getId()]['can_create_profile']);
                $subscription->setCreateProfiles($req_subs[$subscription->getId()]['create_profiles']);
                $subscription->setCanPostPhoto($req_subs[$subscription->getId()]['can_post_photo']);
                $subscription->setPostPhotos($req_subs[$subscription->getId()]['post_photos']);
                $subscription->setCanWink($req_subs[$subscription->getId()]['can_wink']);
                $subscription->setWinks($req_subs[$subscription->getId()]['winks']);
                $subscription->setCanReadMessages($req_subs[$subscription->getId()]['can_read_messages']);
                $subscription->setReadMessages($req_subs[$subscription->getId()]['read_messages']);
                $subscription->setCanReplyMessages($req_subs[$subscription->getId()]['can_reply_messages']);
                $subscription->setReplyMessages($req_subs[$subscription->getId()]['reply_messages']);
                $subscription->setCanSendMessages($req_subs[$subscription->getId()]['can_send_messages']);
                $subscription->setSendMessages($req_subs[$subscription->getId()]['send_messages']);
                $subscription->setCanSeeViewed($req_subs[$subscription->getId()]['can_see_viewed']);
                $subscription->setSeeViewed($req_subs[$subscription->getId()]['see_viewed']);
                $subscription->setCanContactAssistant($req_subs[$subscription->getId()]['can_contact_assistant']);
                $subscription->setContactAssistant($req_subs[$subscription->getId()]['contact_assistant']);
                $subscription->setPreApprove(@$req_subs[$subscription->getId()]['pre_approve']);
                
                $subscription->setTrial1Period($this->getRequestParameter('trial1_period'));
                $subscription->setTrial1PeriodType($this->getRequestParameter('trial1_period_type'));
                $subscription->setTrial1Amount($req_subs[$subscription->getId()]['trial1_amount']);
                $subscription->setTrial2Period($this->getRequestParameter('trial2_period'));
                $subscription->setTrial2PeriodType($this->getRequestParameter('trial2_period_type'));
                $subscription->setTrial2Amount($req_subs[$subscription->getId()]['trial2_amount']);
                $subscription->setPeriod($this->getRequestParameter('period'));
                $subscription->setPeriodType($this->getRequestParameter('period_type'));                
                $subscription->setAmount($req_subs[$subscription->getId()]['amount']);
                $subscription->save();                
            }
        }
        
	    return $this->redirect('subscriptions/list');
    }
    
    $this->subscriptions = $subscriptions;
    $this->sub1 = $subscriptions[0];
  }
}
