<?php
// auto-generated by sfPropelCrud
// date: 2008/05/07 13:20:11
?>
<?php

/**
 * subscriptions actions.
 *
 * @package    pr
 * @subpackage subscriptions
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class subscriptionsActions extends sfActions
{
  public function executeList()
  {
    $this->subscriptions = SubscriptionPeer::doSelect(new Criteria());
  }

  public function executeEdit()
  {
    $subscription = SubscriptionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($subscription);
    
    if( $this->getRequest()->getMethod() == sfRequest::POST )
    {
	    //$subscription->setTitle($this->getRequestParameter('title'));
	    $subscription->setCanPostPhoto($this->getRequestParameter('can_post_photo', 0));
	    $subscription->setPostPhotos($this->getRequestParameter('post_photos'));
	    $subscription->setCanWink($this->getRequestParameter('can_wink', 0));
	    $subscription->setWinks($this->getRequestParameter('winks'));
	    $subscription->setCanReadMessages($this->getRequestParameter('can_read_messages', 0));
	    $subscription->setReadMessages($this->getRequestParameter('read_messages'));
	    $subscription->setCanReplyMessages($this->getRequestParameter('can_reply_messages', 0));
	    $subscription->setReplyMessages($this->getRequestParameter('reply_messages'));
	    $subscription->setCanSendMessages($this->getRequestParameter('can_send_messages', 0));
	    $subscription->setSendMessages($this->getRequestParameter('send_messages'));
	    $subscription->setCanSeeViewed($this->getRequestParameter('can_see_viewed', 0));
	    $subscription->setSeeViewed($this->getRequestParameter('see_viewed'));
	    $subscription->setCanContactAssistant($this->getRequestParameter('can_contact_assistant', 0));
	    $subscription->setContactAssistant($this->getRequestParameter('contact_assistant'));
	    $subscription->setPeriod1From($this->getRequestParameter('period1_from'));
	    $subscription->setPeriod1To($this->getRequestParameter('period1_to'));
	    $subscription->setPeriod1Price($this->getRequestParameter('period1_price'));
	    $subscription->setPeriod2From($this->getRequestParameter('period2_from'));
	    $subscription->setPeriod2To($this->getRequestParameter('period2_to'));
	    $subscription->setPeriod2Price($this->getRequestParameter('period2_price'));
	    $subscription->setPeriod3From($this->getRequestParameter('period3_from'));
	    $subscription->setPeriod3To($this->getRequestParameter('period3_to'));
	    $subscription->setPeriod3Price($this->getRequestParameter('period3_price'));
	    $subscription->setPreApprove($this->getRequestParameter('pre_approve', 0));
	
	    $subscription->save();
	
	    return $this->redirect('subscriptions/list');
    }
    
    $this->sub = $subscription;
  }
}
