<?php
// auto-generated by sfPropelCrud
// date: 2008/12/23 13:28:03
?>
<?php use_helper('Object') ?>

<?php echo form_tag('transCollection/update') ?>

<?php echo object_input_hidden_tag($trans_collection, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($trans_collection, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($trans_collection->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'transCollection/delete?id='.$trans_collection->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'transCollection/show?id='.$trans_collection->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'transCollection/list') ?>
<?php endif; ?>
</form>
