<?php
// auto-generated by sfPropelCrud
// date: 2008/12/23 13:28:03
?>
<h1>transCollection</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
</tr>
</thead>
<tbody>
<?php foreach ($trans_collections as $trans_collection): ?>
<tr>
    <td><?php echo link_to($trans_collection->getId(), 'transCollection/show?id='.$trans_collection->getId()) ?></td>
      <td><?php echo $trans_collection->getName() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'transCollection/create') ?>
