<?php
// auto-generated by sfPropelCrud
// date: 2008/12/23 13:28:03
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $trans_collection->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $trans_collection->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'transCollection/edit?id='.$trans_collection->getId()) ?>
&nbsp;<?php echo link_to('list', 'transCollection/list') ?>
