# default values
all:
  pager:
    default_per_page: 15
    default_pages:    15
  trac:
    url:            trac.nj.bonex.us/cgi-bin/polishromance.fcgi/
    username:       pr_client_reports
    password:       100kalpaka+1004ereshi
    ticket_type:    "Client Report"
    milestone:      "Client Reports"