rendering: ~
web_debug: ~
security:  ~
cancel:
  class:  confirmMessageFilter
referer:
    class:  refererFilter
    param:
        namespace:  backend/user/referer_stack
cache:     ~
common:    ~
flash:     ~
execution: ~
