rendering: ~
web_debug: ~
security:
  enabled:  false
newSecurity:
  class: sfNewSecurity
cancel:
  class:  confirmMessageFilter
# generally, you will want to insert your own filters here

cache:     ~
common:    ~
flash:     ~
execution: ~
