rendering: ~
web_debug: ~
security:  ~
cancel:
  class:  confirmMessageFilter
referer:
    class:  refererFilter
    param:
        namespace:  backend/user/referer_stack
mustChangePwd:
    enabled: yes
    class:  mustChangePwdFilter
    param:
        password_action: users/myAccount        
cache:     ~
common:    ~
flash:     ~
execution: ~
