# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: list }

default:
  url:   /:module/:action/*
