default:
  http_metas:
    content-type: text/html

  metas:
    title:        PolishRomance.com - Admin Tool
    robots:       noindex, nofollow
    description:  PolishRomance.com - Admin Tool
    keywords:     PolishRomance.com - Admin Tool
    language:     en

  stylesheets:    [reset, form_admin, main_admin]

  javascripts:    [zebra]

  has_layout:     on
  layout:         layout
