<?php
class dbSettingsConfigHandler
{

    public function initialize()
    {
    }

    public function execute($configFiles)
    {
        $databaseManager = new sfDatabaseManager();
        $databaseManager->initialize();
        

        $retval = "<?php\n";
        $retval .= "// auto-generated by ".__CLASS__."\n";
        $retval .= "// date: ".date('Y/m/d H:i:s')."\n";
        
        $catalogs = CataloguePeer::doSelect(new Criteria());
        
        foreach($catalogs as $catalog)
        {
            $settings = sfSettingPeer::getByCatalog($catalog);
            
            $data = '';
            foreach ($settings as $p)
            {
                $data .= sprintf("  'app_settings_%s' => %s,\n", $p->getName(), var_export($p->getValue(), true));
            }
            
            $domain = $catalog->getDomain();
            $catalog_domains = sfConfig::get('app_catalog_domains'); //dev catalogs
            $key = array_search($domain, $catalog_domains);
            if( $key !== FALSE) $domain = $key;

            $retval .= sprintf("if(\$_SERVER['HTTP_HOST'] == '%s') sfConfig::add(array(\n%s));\n", $domain, $data);
        }
        

        return $retval;
    }
}
