<?php
class dbSettingsConfigHandler
{

    public function initialize()
    {
    }

    public function execute($configFiles)
    {
        $databaseManager = new sfDatabaseManager();
        $databaseManager->initialize();
        
        $retval = "<?php\n" . "// auto-generated by " . __CLASS__ . "\n" . "// date: " . date('Y/m/d H:i:s') . "\n";
        $settings = sfSettingPeer::doSelect(new Criteria());
        
        foreach ($settings as $p)
        {
            if ($p->getName())
            {
                $val = trim($p->getValue(), '"');
                $val = trim($val, "'");
                
                if (! is_null($val) && $val != '')
                    $retval .= sprintf("sfConfig::set('app_settings_%s', '%s');\n", $p->getName(), $val);
            }
        }
        
        $retval .= "?>\n";
        return $retval;
    }
}
