<?php
// auto-generated by sfPropelCrud
// date: 2008/07/17 15:31:12
?>
<?php use_helper('Object') ?>

<?php echo form_tag('staticPagesCrud/update') ?>

<?php echo object_input_hidden_tag($static_page, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Slug*:</th>
  <td><?php echo object_input_tag($static_page, 'getSlug', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Title*:</th>
  <td><?php echo object_input_tag($static_page, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($static_page->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'staticPagesCrud/delete?id='.$static_page->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'staticPagesCrud/show?id='.$static_page->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'staticPagesCrud/list') ?>
<?php endif; ?>
</form>
