<?php
// auto-generated by sfPropelCrud
// date: 2008/07/17 15:31:12
?>
<h1>staticPagesCrud</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Slug</th>
</tr>
</thead>
<tbody>
<?php foreach ($static_pages as $static_page): ?>
<tr>
    <td><?php echo link_to($static_page->getId(), 'staticPagesCrud/show?id='.$static_page->getId()) ?></td>
      <td><?php echo $static_page->getSlug() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'staticPagesCrud/create') ?>
