<?php
// auto-generated by sfPropelCrud
// date: 2008/05/05 14:07:07
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $imbra_reply_template->getId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $imbra_reply_template->getTitle() ?></td>
</tr>
<tr>
<th>Subject: </th>
<td><?php echo $imbra_reply_template->getSubject() ?></td>
</tr>
<tr>
<th>Body: </th>
<td><?php echo $imbra_reply_template->getBody() ?></td>
</tr>
<tr>
<th>Mail from: </th>
<td><?php echo $imbra_reply_template->getMailFrom() ?></td>
</tr>
<tr>
<th>Reply to: </th>
<td><?php echo $imbra_reply_template->getReplyTo() ?></td>
</tr>
<tr>
<th>Bcc: </th>
<td><?php echo $imbra_reply_template->getBcc() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'imbraReplyTemplates/edit?id='.$imbra_reply_template->getId()) ?>
&nbsp;<?php echo link_to('list', 'imbraReplyTemplates/list') ?>
