selfDescriptionSuccess:
    javascripts: [/sf/prototype/js/prototype, show_hide_other]
essaySuccess:
    javascripts: [ charcount, essay_polish_letters ]
photosSuccess:
    javascripts: [ check_upload_field ]    