<?php
// auto-generated by sfPropelCrud
// date: 2008/08/01 09:57:51
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $desc_answer->getId() ?></td>
</tr>
<tr>
<th>Desc question: </th>
<td><?php echo $desc_answer->getDescQuestion() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $desc_answer->getTitle() ?></td>
</tr>
<tr>
<th>Search title: </th>
<td><?php echo $desc_answer->getSearchTitle() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'descAnswerCrud/edit?id='.$desc_answer->getId()) ?>
&nbsp;<?php echo link_to('list', 'descAnswerCrud/list') ?>
&nbsp;<?php echo link_to ('create', 'descAnswerCrud/create?question_id=' . $desc_answer->getDescQuestionId()) ?>
