all:
  sf_google_analytics_plugin:
    enabled:                no
    classes:
      google2:   sfGoogleAnalyticsTrackerGoogle2
  sfSimpleGoogleSitemap:
    orm:                  Propel                 # possible values: auto, Propel, DbFinder. 'auto' is auto detection. Note: case sensitive!
    urls:                                        # define multiple static urls here
      homepage:                                  # just a name
        url:              @homepage              # route
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         1.0                    # 1.0 is top priority (100%) compared to 0.2 which is less priority (20%)
      join_now:
        url:              @joinnow
        freq:             monthly
        priority:         0.5
      sign_in:
        url:              @signin
        freq:             monthly
        priority:         0.5
      tell_friend:
        url:              content/tellFriend
        freq:             monthly
        priority:         0.5
    models:                                      # define multiple models to generate sitemap from
      model_pages:                               # just a name
        model:            StaticPage       # model class name
        propel_method:    doSelectWithI18n
        route:            content/page
        params:                                  # parameters for the url
          slug:           getSlug       # name : method to get the parameter value
        date:             getUpdatedAt           # method to get date last updated for the url
        criteria:                                # criterias to filter the records to include in the sitemap
          - { column: has_content, method: getHasContent, operator: = , value: 1 }
        order_by:         { peer: StaticPageI18nPeer, column: TITLE, method: Title, sort: asc }
        freq:             weekly                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_pages:
        model:            MemberStory
        propel_method:    doSelect
        route:            memberStories/read
        params:
          slug:           getSlug
        date:             getUpdatedAt
        order_by:         { peer: MemberStoryPeer, column: SORT_ORDER, method: SortOrder, sort: asc }
        freq:             weekly
        priority:         0.5
      model_profiles:
        model:            Member
        route:            @public_profile
        params:
          username:       getUsername
        date:             getLastLogin
        criteria:
          - { column: member_status_id, method: getMemberStatusId, operator: = , value: 1 }
          - { column: private_dating, method: getPrivateDating, operator: = , value: 0 }
        order_by:         { peer: MemberPeer, column: CREATED_AT, method: CreatedAt, sort: desc }
        freq:             daily
        priority:         0.5
  cse_id:
      en:   "014252771680410157097:dm1temprble"
      pl:   "014252771680410157097:cjbkxr0dyga"

  dotpay:
    url:        https://ssl.dotpay.pl/
    ip_address: "195.150.9.37"
  dotpay_sms:
    account_id: 20767
    secret: I92JsuHT04r6fZNl
    prefix: TC.WHIN
    number: 92595

  gifts:
    friends_limit: 2 # maximum gifts to send after payment
    send_period_days: 7 #member can send gift for that long after last payment
    expire_days: 7 #unaccepted gift expires after this period in days
    free_period_days: 14 #free subscription period in days
  pusher:
    key: 15626cff3028b13b38a2
    secret: 6e61917d1434b046e930
    app_id: 117716
dev:
  gmaps_key:
    pd_dincho_bonex_us:         ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pl_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pr_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    devel_pd_dincho_bonex_us:   ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    branch_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    ec_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    mm_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
  paypal:
    business:             pd-seller@gmail.com
    test:                 yes
    url:                  https://www.sandbox.paypal.com/cgi-bin/webscr
    cert_id:              8RBU44QFHS9BQ
    notify_url:           http://pd.dincho.bonex.us:8007/frontend_dev.php/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/sandbox_pr-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/sandbox_pr-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/sandbox_paypal-pubcert.pem
  zong:
      customer_key:         polishdev
      supported_countries:  [PL, US]
      accept_simulated:     yes
  dotpay:
    account_id:           20767
    secret:               I92JsuHT04r6fZNl
    callback_url:         http://pd.dincho.bonex.us:8007/frontend_dev.php/callbacks/dotpay.html
    test_mode:            yes

  title_prefix:
    polishdate_bonex_us:     "PolishDate (dev) - "
    pl_polishdate_bonex_us:  "SzukamMilionera.com (dev) - "
    mm_polishdate_bonex_us:  "MeskaMilosc.pl (dev) - "
  sf_google_analytics_plugin:
    enabled:                no
  dotpay_sms:
    prefix: TC.PDTEST

stag:
  gmaps_key:
    polishdate_bonex_us:          ABQIAAAAZ8CWR0Ug1byIqYVeuFfIYhT1t4zxXDUL8-uvkn_t4boESsZvkhRnb6N6jyVnR8UNM-tg1IE552KCJg
    pl_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
    mm_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
    cs_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
    db_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
    as_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
    im_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
  paypal:
    business:             pd-seller@gmail.com
    test:                 yes
    url:                  https://www.sandbox.paypal.com/cgi-bin/webscr
    cert_id:              8RBU44QFHS9BQ
    notify_url:           http://polishdate.bonex.us/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/sandbox_pr-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/sandbox_pr-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/sandbox_paypal-pubcert.pem
  zong:
      customer_key:         polishdev
      supported_countries:  [PL, US]
      accept_simulated:     yes
  dotpay:
    account_id:           20767
    secret:               I92JsuHT04r6fZNl
    callback_url:         http://polishdate.bonex.us/callbacks/dotpay.html
    test_mode:            yes
  title_prefix:
    polishdate_bonex_us:     "PolishDate (stag) - "
    pl_polishdate_bonex_us:  "SzukamMilionera.com (stag) - "
    mm_polishdate_bonex_us:  "MeskaMilosc.pl (stag) - "
    cs_polishdate_bonex_us:  "CafeSayang.com (stag) - "
    db_polishdate_bonex_us:  "DatingBistro.com (stag) - "
    as_polishdate_bonex_us:  "Ashley.pl (stag) - "
    im_polishdate_bonex_us:  "IshchuMillionera.com (stag) - "
  sf_google_analytics_plugin:
    enabled:                no
  pusher:
    key: 94007b2c2e593269d60e
    secret: 80f6fc5b388d8f62e32d
    app_id: 117717
  dotpay_sms:
    prefix: TC.PDSTAG

test:
  paypal:
    business:             pd-seller@gmail.com
    test:                 yes
    url:                  https://www.sandbox.paypal.com/cgi-bin/webscr
    cert_id:              8RBU44QFHS9BQ
    notify_url:           http://pd.dincho.bonex.us:8007/frontend_dev.php/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/sandbox_pr-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/sandbox_pr-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/sandbox_paypal-pubcert.pem
  zong:
      customer_key:         polishdev
      supported_countries:  [PL, US]
      accept_simulated:     yes
prod:
  gmaps_key:
    www_polishdate_com:       AIzaSyC6oAx7kFEdlN6VAytEeFLDGHsVaflr85E
    www_szukammilionera_com:  AIzaSyC6oAx7kFEdlN6VAytEeFLDGHsVaflr85E
    www_meskamilosc_pl:       AIzaSyC6oAx7kFEdlN6VAytEeFLDGHsVaflr85E
    www_cafesayang_com:       AIzaSyC6oAx7kFEdlN6VAytEeFLDGHsVaflr85E
    www_datingbistro_com:     AIzaSyC6oAx7kFEdlN6VAytEeFLDGHsVaflr85E
    www_ashley_pl:            AIzaSyC6oAx7kFEdlN6VAytEeFLDGHsVaflr85E
    www_ishchumillionera_com: AIzaSyC6oAx7kFEdlN6VAytEeFLDGHsVaflr85E
  paypal:
    old_business:         futurise@gmail.com
    business:             administrator@inventiss.com
    url:                  https://www.paypal.com/cgi-bin/webscr
    cert_id:              VGR2LFT7E8CWE
    notify_url:           http://PolishDate.com/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/polishdate-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/polishdate-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/paypal_pubcert.pem
  zong:
      customer_key:         polish
      supported_countries:  [US]
      accept_simulated:     no
  dotpay:
    account_id:           60847
    secret:               gooTh2pouNg4neif
    callback_url:         http://www.polishdate.com/callbacks/dotpay.html
  title_prefix:
    www_polishdate_com:       "PolishDate - "
    www_szukammilionera_com:  "SzukamMilionera.com - "
    www_meskamilosc_pl:       "MeskaMilosc.pl - "
    www_cafesayang_com:       "CafeSayang.com - "
    www_datingbistro_com:     "DatingBistro.com - "
    www_ashley_pl:            "Ashley.pl - "
    www_ishchumillionera_com: "IshchuMillionera.com - "
  sf_google_analytics_plugin:
    enabled:      yes
    profile_id:   UA-11123315-1
    tracker:      google2
    insertion:    bottom
    params:
      domain_name:   none
      linker_policy: true
  pusher:
    key: a40fb1a471cd1e5e3c38
    secret: 6a7a16d07116a37f7430
    app_id: 117718
