all:
  gmaps_key:
    pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pl_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pr_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    devel_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    branch_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
  paypal:
    business: admin_1231849319_biz@polishromance.com
    test:     1
    cert_id:  9CKZZ95GS2NCL
    url:      https://www.sandbox.paypal.com/cgi-bin/webscr
    #notify_url: http://pd.dincho.bonex.us:8003/IPN.html #this URL should be always absolute!!!
    notify_url: http://pd.dincho.bonex.us/IPN.html
  sf_google_analytics_plugin:
    enabled:      off
    profile_id:   UA-11123315-1
    tracker:      google
    insertion:    top
    params:
      domain_name:   none
      linker_policy: true    
  title_prefix:
    pd_dincho_bonex_us:  "PolishDate - "
    pl_pd_dincho_bonex_us:  "LoveStreet.pl - "
