all:
  gmaps_key:
    pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pl_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pr_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    devel_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    branch_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
  paypal:
    business:             admin_1231849319_biz@polishromance.com
    test:                 yes
    url:                  https://www.sandbox.paypal.com/cgi-bin/webscr
    #notify_url: http://pd.dincho.bonex.us:8007/callbacks/paypal.html #this URL should be always absolute!!! ( because of the different enviroments )
    cert_id:              KRHQZEWMCEYVL
    notify_url:           http://pd.dincho.bonex.us/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/sandbox_pr-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/sandbox_pr-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/sandbox_paypal-pubcert.pem
    
  zong:
      customer_key:         polishdev
      items_currency:       PLN
      amount:               100
      supported_countries:  [PL]
      accept_simulated:     true
  sf_google_analytics_plugin:
    enabled:      off
    profile_id:   UA-11123315-1
    tracker:      google
    insertion:    top
    params:
      domain_name:   none
      linker_policy: true    
  title_prefix:
    pd_dincho_bonex_us:  "PolishDate - "
    pl_pd_dincho_bonex_us:  "SzukamMilionera.com - "
    www_polishdate_com:  "PolishDate - "
    www_szukammilionera_com:  "SzukamMilionera.com - "
  sfSimpleGoogleSitemap:
    orm:                  Propel                 # possible values: auto, Propel, DbFinder. 'auto' is auto detection. Note: case sensitive!
    urls:                                        # define multiple static urls here
      homepage:                                  # just a name
        url:              @homepage              # route
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         1.0                    # 1.0 is top priority (100%) compared to 0.2 which is less priority (20%)
      join_now:
        url:              @joinnow
        freq:             monthly
        priority:         0.5
      sign_in:
        url:              @signin
        freq:             monthly
        priority:         0.5
      tell_friend:
        url:              content/tellFriend
        freq:             monthly
        priority:         0.5
    models:                                      # define multiple models to generate sitemap from
      model_pages:                               # just a name
        model:            StaticPage       # model class name
        propel_method:    doSelectWithI18n
        route:            content/page
        params:                                  # parameters for the url
          slug:           getSlug       # name : method to get the parameter value
        date:             getUpdatedAt           # method to get date last updated for the url
        criteria:                                # criterias to filter the records to include in the sitemap
          - { column: has_content, method: getHasContent, operator: = , value: 1 }
        order_by:         { peer: StaticPageI18nPeer, column: TITLE, method: Title, sort: asc }
        freq:             weekly                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_pages:
        model:            MemberStory
        propel_method:    doSelectJoinStockPhotoWithCurrentCulture
        route:            memberStories/read
        params:
          slug:           getSlug
        date:             getUpdatedAt
        order_by:         { peer: MemberStoryPeer, column: SORT_ORDER, method: SortOrder, sort: asc }
        freq:             weekly
        priority:         0.5  
      model_profiles:
        model:            Member
        route:            @public_profile
        params:
          username:       getUsername
        date:             getLastLogin
        criteria:
          - { column: member_status_id, method: getMemberStatusId, operator: = , value: 1 }
          - { column: private_dating, method: getPrivateDating, operator: = , value: 0 }
        order_by:         { peer: MemberPeer, column: CREATED_AT, method: CreatedAt, sort: desc }
        freq:             daily
        priority:         0.5
  cse_id:
      en:   "014252771680410157097:dm1temprble"
      pl:   "014252771680410157097:cjbkxr0dyga"