all:
  recaptcha:
    pd_dincho_bonex_us:
      publickey:            "6LdbDLwSAAAAAEp3Q-HDwVHekC1cvIWMxS7d4tgS" #global-key.bonex.us
      privatekey:           "6LdbDLwSAAAAAONCW9MOZZAT0QhzLcU3YpChG8fW"
    pl_pd_dincho_bonex_us:
      publickey:            "6LdbDLwSAAAAAEp3Q-HDwVHekC1cvIWMxS7d4tgS" #global-key.bonex.us
      privatekey:           "6LdbDLwSAAAAAONCW9MOZZAT0QhzLcU3YpChG8fW"
    devel_pd_dincho_bonex_us:
      publickey:            "6LdbDLwSAAAAAEp3Q-HDwVHekC1cvIWMxS7d4tgS" #global-key.bonex.us
      privatekey:           "6LdbDLwSAAAAAONCW9MOZZAT0QhzLcU3YpChG8fW"
    branch_pd_dincho_bonex_us:
      publickey:            "6LdbDLwSAAAAAEp3Q-HDwVHekC1cvIWMxS7d4tgS" #global-key.bonex.us
      privatekey:           "6LdbDLwSAAAAAONCW9MOZZAT0QhzLcU3YpChG8fW"
    ec_pd_dincho_bonex_us:
      publickey:            "6LdbDLwSAAAAAEp3Q-HDwVHekC1cvIWMxS7d4tgS" #global-key.bonex.us
      privatekey:           "6LdbDLwSAAAAAONCW9MOZZAT0QhzLcU3YpChG8fW"
    mm_pd_dincho_bonex_us:
      publickey:            "6LdbDLwSAAAAAEp3Q-HDwVHekC1cvIWMxS7d4tgS" #global-key.bonex.us
      privatekey:           "6LdbDLwSAAAAAONCW9MOZZAT0QhzLcU3YpChG8fW"      
  sf_google_analytics_plugin:
    enabled:                no
  sfSimpleGoogleSitemap:
    orm:                  Propel                 # possible values: auto, Propel, DbFinder. 'auto' is auto detection. Note: case sensitive!
    urls:                                        # define multiple static urls here
      homepage:                                  # just a name
        url:              @homepage              # route
        freq:             daily                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         1.0                    # 1.0 is top priority (100%) compared to 0.2 which is less priority (20%)
      join_now:
        url:              @joinnow
        freq:             monthly
        priority:         0.5
      sign_in:
        url:              @signin
        freq:             monthly
        priority:         0.5
      tell_friend:
        url:              content/tellFriend
        freq:             monthly
        priority:         0.5
    models:                                      # define multiple models to generate sitemap from
      model_pages:                               # just a name
        model:            StaticPage       # model class name
        propel_method:    doSelectWithI18n
        route:            content/page
        params:                                  # parameters for the url
          slug:           getSlug       # name : method to get the parameter value
        date:             getUpdatedAt           # method to get date last updated for the url
        criteria:                                # criterias to filter the records to include in the sitemap
          - { column: has_content, method: getHasContent, operator: = , value: 1 }
        order_by:         { peer: StaticPageI18nPeer, column: TITLE, method: Title, sort: asc }
        freq:             weekly                  # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.5                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_pages:
        model:            MemberStory
        propel_method:    doSelect
        route:            memberStories/read
        params:
          slug:           getSlug
        date:             getUpdatedAt
        order_by:         { peer: MemberStoryPeer, column: SORT_ORDER, method: SortOrder, sort: asc }
        freq:             weekly
        priority:         0.5  
      model_profiles:
        model:            Member
        route:            @public_profile
        params:
          username:       getUsername
        date:             getLastLogin
        criteria:
          - { column: member_status_id, method: getMemberStatusId, operator: = , value: 1 }
          - { column: private_dating, method: getPrivateDating, operator: = , value: 0 }
        order_by:         { peer: MemberPeer, column: CREATED_AT, method: CreatedAt, sort: desc }
        freq:             daily
        priority:         0.5
  cse_id:
      en:   "014252771680410157097:dm1temprble"
      pl:   "014252771680410157097:cjbkxr0dyga"          
    
  dotpay:
    account_id: 44199
    url:        https://ssl.dotpay.pl/
    secret:     RilS480Z1rqLF3Ee
    ip_address: "195.150.9.37"

dev:
  gmaps_key:
    pd_dincho_bonex_us:         ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pl_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    pr_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    devel_pd_dincho_bonex_us:   ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    branch_pd_dincho_bonex_us:  ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    ec_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
    mm_pd_dincho_bonex_us:      ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BSZHOM69ArWeLydefi213lCfJxAdxRI-S73zrRwJIyVR_FzKaZYx5-eIg
  paypal:
    business:             admin_1231849319_biz@polishromance.com
    test:                 yes
    url:                  https://www.sandbox.paypal.com/cgi-bin/webscr
    cert_id:              KRHQZEWMCEYVL
    notify_url:           http://pd.dincho.bonex.us:8007/frontend_dev.php/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/sandbox_pr-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/sandbox_pr-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/sandbox_paypal-pubcert.pem
  zong:
      customer_key:         polishdev
      supported_countries:  [PL, US]
      accept_simulated:     yes
  dotpay:
    callback_url:         http://pd.dincho.bonex.us:8007/frontend_dev.php/callbacks/dotpay.html
    test_mode:            yes
    
  title_prefix:
    pd_dincho_bonex_us:     "PolishDate (dev) - "
    pl_pd_dincho_bonex_us:  "SzukamMilionera.com (dev) - "
    ec_pd_dincho_bonex_us:  "ExpatCalling.com (dev) - "
    mm_pd_dincho_bonex_us:  "MeskaMilosc.pl (dev) - "
  sf_google_analytics_plugin:
    enabled:                no
    
stag:
  gmaps_key:
    polishdate_bonex_us:          ABQIAAAAZ8CWR0Ug1byIqYVeuFfIYhT1t4zxXDUL8-uvkn_t4boESsZvkhRnb6N6jyVnR8UNM-tg1IE552KCJg
    pl_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
    ec_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
    mm_polishdate_bonex_us:       ABQIAAAAWOdXT6qNUgPjKm7xCk2W8BT1t4zxXDUL8-uvkn_t4boESsZvkhR6bhP-eezmr93L4qM2DynVHf8Hyg
  paypal:
    business:             admin_1231849319_biz@polishromance.com
    test:                 yes
    url:                  https://www.sandbox.paypal.com/cgi-bin/webscr
    cert_id:              KRHQZEWMCEYVL
    notify_url:           http://polishdate.bonex.us/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/sandbox_pr-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/sandbox_pr-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/sandbox_paypal-pubcert.pem
  zong:
      customer_key:         polishdev
      supported_countries:  [PL, US]
      accept_simulated:     yes
  dotpay:
    callback_url:         http://polishdate.bonex.us/callbacks/dotpay.html
    test_mode:            yes
  title_prefix:
    pd_dincho_bonex_us:     "PolishDate (stag) - "
    pl_pd_dincho_bonex_us:  "SzukamMilionera.com (stag) - "
    ec_pd_dincho_bonex_us:  "ExpatCalling.com (stag) - "
    mm_pd_dincho_bonex_us:  "MeskaMilosc.pl (stag) - "
  sf_google_analytics_plugin:
    enabled:                no  
      
prod:
  gmaps_key:
    www_polishdate_com:       ABQIAAAAOxJQPDtbbVztfX1WpxwrshQaophwVwW_eBIBsKwHigAlAJr07BQan0Q--w8XgzEZJixvvisTR8s4RQ
    www_szukammilionera_com:  ABQIAAAAZ8CWR0Ug1byIqYVeuFfIYhTZijEIVzSftDK0MzXXzUJavTzaphT1XeeYNHbUE4T-nno3v2PWQpKoSQ
    www_expatcalling_com:     ABQIAAAAZ8CWR0Ug1byIqYVeuFfIYhTVq_jkNdk7c3EunQ0bhNQklpYTghRhnRWLGHE9840MvMDdJmIAGaAaLw
    www_meskamilosc_pl:       ABQIAAAAZ8CWR0Ug1byIqYVeuFfIYhSTx2cZH2anLpRmckr8Ru6pruWHXRRRc6-x87-_nzejI15G2wtjIwlGfg
  recaptcha:
    www_polishdate_com:
      publickey:            "6LdYDLwSAAAAAPx-nYdDnatkNHMO5z5SEY_zS_xj"
      privatekey:           "6LdYDLwSAAAAAJimpEAAo5FJH47QSfHB6XpDfZRt"
    www_szukammilionera_com:
      publickey:            "6LepC7wSAAAAAOhZJiIVZmqC-wyANP63_5jEwyzM"
      privatekey:           "6LepC7wSAAAAAE5UWS9O2KZHy8Q3REx9ICvid2rq"
    www_meskamilosc_pl:
      publickey:            "6LeQ8bwSAAAAAKFI1hfhketTw3fK2GuJ9ZQvHlmN"
      privatekey:           "6LeQ8bwSAAAAADjGUNiAG9IAsnWQmgpwWjnTiP-D"
    www_expatcalling_com:
      publickey:            "6Lf26bwSAAAAAEDae5UVuOwzRSmx7rJZpIizO0i2"
      privatekey:           "6Lf26bwSAAAAALF-dabveoS-4vpq8F8pZq0j0Zz6"
  paypal:
    business:             futurise@gmail.com
    url:                  https://www.paypal.com/cgi-bin/webscr
    cert_id:              H3GYCU4KQESRQ
    notify_url:           http://PolishDate.com/callbacks/paypal.html
    cert_public:          %SF_DATA_DIR%/paypal/polishdate-pubcert.pem
    cert_private_key:     %SF_DATA_DIR%/paypal/polishdate-prvkey.pem
    cert_public_paypal:   %SF_DATA_DIR%/paypal/paypal_pubcert.pem
  zong:
      customer_key:         polish
      supported_countries:  [US]
      accept_simulated:     no
  dotpay:
    callback_url:         http://www.polishdate.com/callbacks/dotpay.html
  title_prefix:
    www_polishdate_com:       "PolishDate - "
    www_szukammilionera_com:  "SzukamMilionera.com - "
    www_expatcalling_com:     "ExpatCalling.com - "
    www_meskamilosc_pl:       "MeskaMilosc.pl - "
  sf_google_analytics_plugin:
    enabled:      yes
    profile_id:   UA-11123315-1
    tracker:      google
    insertion:    top
    params:
      domain_name:   none
      linker_policy: true      