cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage

all:
  controller:
    class: sfFrontWebController

  request:
    class: sfWebRequest

  response:
    class: prWebResponse

  user:
    class: myUser

  storage:
    class: dtMySQLSessionStorage
    param:
      session_name: polishRomance
      database: propel
      db_table: session_storage

  view_cache:
    class: sfFileCache
    param:
      automaticCleaningFactor: 0
      cacheDir:                %SF_TEMPLATE_CACHE_DIR%
