cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage

all:
  controller:
    class: sfFrontWebController

  request:
    class: sfWebRequest

  response:
    class: prWebResponse

  user:
    class: myUser

  storage:
    class: prMySQLSessionStorage
    param:
      session_name: PDSSID
      database: propel
      db_table: session_storage
