title:
    class:  titleFilter
rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here
status:
    class:  statusFilter
mustChangePwd:
    enabled: yes
    class:  mustChangePwdFilter
    param:
        password_action: editProfile/registration
referer:
    class:  refererFilter
    param:
        namespace:  frontend/member/referer_stack

cache:     ~
common:    ~
flash:     ~
execution: ~
