title:
    class:  titleFilter
rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here
sessionVarRedirect:
    class: SessionVarRedirectFilter

ipblock:
    class: ipblockFilter
status:
    class:  statusFilter
imbraPayment:
    class:  imbraPaymentFilter
mustChangePwd:
    enabled: yes
    class:  mustChangePwdFilter
    param:
        password_action: editProfile/registration
referer:
    class:  refererFilter
    param:
        namespace:  frontend/member/referer_stack

domainsFilter:
    class: DomainsFilter
            
cache:     ~
#common:    ~

common:    
  class: sfOptimizeStyleAndScript
  
flash:     ~
execution: ~
