title:
    class:  titleFilter
rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here
sessionVarRedirect:
    class: SessionVarRedirectFilter

ipblock:
    class: ipblockFilter
status:
    class:  statusFilter
FVrequired:
    class:  FVrequiredFilter
deactivation:
    class:  deactivationFilter
    enabled: <?php echo (sfConfig::get('app_settings_deactivation_counter') > 0) ? 'yes' : 'no', "\n"; ?>
mustChangePwd:
    enabled: yes
    class:  mustChangePwdFilter
    param:
        password_action: editProfile/registration
referer:
    class:  refererFilter
    param:
        namespace:  frontend/member/referer_stack

domainsFilter:
    class: DomainsFilter

sf_google_analytics_plugin:
  class: sfGoogleAnalyticsFilter
             
cache:     ~

common:
    class: <?php echo (SF_ENVIRONMENT == 'dev') ? 'sfCommonFilter' : 'sfOptimizeStyleAndScript', "\n" ?>
  
flash:     ~
execution: ~
