default:
  http_metas:
    content-type: text/html

  metas:
    title:        LoveStreet.pl
    robots:       index, follow
    description:  Love Street
    keywords:     love, street
    language:     en

  stylesheets:    [main]

  javascripts:    [/sf/prototype/js/prototype.js, active_fields.js]

  has_layout:     on
  layout:         layout
