default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: IE=EmulateIE8
          
  metas:
    title:        SzukamMilionera.com
    robots:       index, follow
    description:  Love Street
    keywords:     love, street
    language:     en

  stylesheets:    [main]

  javascripts:    [/sf/prototype/js/prototype.js, active_fields.js, recaptcha_options.js, dropdown.js ]

  has_layout:     on
  layout:         layout
