<?php
// auto-generated by sfPropelCrud
// date: 2008/08/01 09:46:50
?>
<?php use_helper('Object') ?>

<?php echo form_tag('descQuestionCrud/update') ?>

<?php echo object_input_hidden_tag($desc_question, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($desc_question, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Search title:</th>
  <td><?php echo object_input_tag($desc_question, 'getSearchTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Type:</th>
  <td><?php echo object_input_tag($desc_question, 'getType', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($desc_question->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'descQuestionCrud/delete?id='.$desc_question->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'descQuestionCrud/show?id='.$desc_question->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'descQuestionCrud/list') ?>
<?php endif; ?>
</form>
