<?php
// auto-generated by sfPropelCrud
// date: 2008/08/01 09:46:50
?>
<h1>descQuestionCrud</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Title</th>
  <th>Search title</th>
  <th>Type</th>
</tr>
</thead>
<tbody>
<?php foreach ($desc_questions as $desc_question): ?>
<tr>
    <td><?php echo link_to($desc_question->getId(), 'descQuestionCrud/show?id='.$desc_question->getId()) ?></td>
      <td><?php echo $desc_question->getTitle() ?></td>
      <td><?php echo $desc_question->getSearchTitle() ?></td>
      <td><?php echo $desc_question->getType() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'descQuestionCrud/create') ?>
