<?php
// auto-generated by sfPropelCrud
// date: 2008/08/01 09:46:50
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $desc_question->getId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $desc_question->getTitle() ?></td>
</tr>
<tr>
<th>Search title: </th>
<td><?php echo $desc_question->getSearchTitle() ?></td>
</tr>
<tr>
<th>Type: </th>
<td><?php echo $desc_question->getType() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'descQuestionCrud/edit?id='.$desc_question->getId()) ?>
&nbsp;<?php echo link_to('list', 'descQuestionCrud/list') ?>
