<?php
// auto-generated by sfPropelCrud
// date: 2008/12/23 13:27:40
?>
<?php use_helper('Object') ?>

<?php echo form_tag('msgCollection/update') ?>

<?php echo object_input_hidden_tag($msg_collection, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Trans collection:</th>
  <td><?php echo object_select_tag($msg_collection, 'getTransCollectionId', array (
  'related_class' => 'TransCollection',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($msg_collection, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($msg_collection->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'msgCollection/delete?id='.$msg_collection->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'msgCollection/show?id='.$msg_collection->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'msgCollection/list') ?>
<?php endif; ?>
</form>
