<?php
// auto-generated by sfPropelCrud
// date: 2008/12/23 13:27:40
?>
<h1>msgCollection</h1>

<?php echo link_to ('create', 'msgCollection/create') ?>
<table>
<thead>
<tr>
  
  <th>Trans collection</th>
  <th>Name</th>
  <th>Id</th>
</tr>
</thead>
<tbody>
<?php foreach ($msg_collections as $msg_collection): ?>
<tr>
    <td><?php echo $msg_collection->getTransCollection() ?></td>
    <td><?php echo link_to($msg_collection->getName(), 'msgCollection/edit?id='.$msg_collection->getId()) ?></td>
    <td><?php echo link_to($msg_collection->getId(), 'msgCollection/edit?id='.$msg_collection->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'msgCollection/create') ?>
