<?php
// auto-generated by sfPropelCrud
// date: 2008/12/23 13:27:40
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $msg_collection->getId() ?></td>
</tr>
<tr>
<th>Trans collection: </th>
<td><?php echo $msg_collection->getTransCollectionId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $msg_collection->getName() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'msgCollection/edit?id='.$msg_collection->getId()) ?>
&nbsp;<?php echo link_to('list', 'msgCollection/list') ?>
