<?php
// auto-generated by sfPropelCrud
// date: 2008/03/20 22:45:15
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $user->getId() ?></td>
</tr>
<tr>
<th>User status: </th>
<td><?php echo $user->getStatus() ?></td>
</tr>
<tr>
<th>Username: </th>
<td><?php echo $user->getUsername() ?></td>
</tr>
<tr>
<th>Password: </th>
<td><?php echo $user->getPassword() ?></td>
</tr>
<tr>
<th>First name: </th>
<td><?php echo $user->getFirstName() ?></td>
</tr>
<tr>
<th>Last name: </th>
<td><?php echo $user->getLastName() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $user->getEmail() ?></td>
</tr>
<tr>
<th>Phone: </th>
<td><?php echo $user->getPhone() ?></td>
</tr>
<tr>
<th>Must change pwd: </th>
<td><?php echo $user->getMustChangePwd() ?></td>
</tr>
<tr>
<th>Is superuser: </th>
<td><?php echo $user->getIsSuperuser() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $user->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'users/edit?id='.$user->getId()) ?>
&nbsp;<?php echo link_to('list', 'users/list') ?>
