default:
    beta_period:        off
    brand_text:         LoveStreet.pl
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    base_domain:        pd.dincho.bonex.us #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             pl.pd.dincho.bonex.us
    version:            "v1.2.3/HEAD"
    mail:
        host:           imap.emailsrvr.com
        port:           143 #should be 993 on production/test server
        username:       autocheck@polishromance.com
        password:       dincho
        from:           admin@PolishRomance.com
        mailer:         smtp
        smtp_host:      smtp.emailsrvr.com
        smtp_username:  admin@polishromance.com
        smtp_password:  polish_romance
