all:
    beta_period:        off
    brand_text:         SzukamMilionera.com
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    version:            "v1.7.5"
    sfImageTransformPlugin:
      mime_type:
        auto_detect: true
        library: gd_mime_type # Fileinfo (PECL), MIME_Type (PEAR), gd_mime_type (GD)
      font_dir: %SF_DATA_DIR%/fonts/
    mail:
     class:             prMail
     enabled:           no
     use_queue:         no
     phpmailer_exceptions:   yes
     rethrow_exception:      no
     smtp_debug:        0
     incoming:
        host:           imap.gmail.com
        port:           993
        username:       incoming@polishdate.com
        password:       PD11837
     rr_groups: #the values should match the outgoing keys below
         - GR1:
             title: "Round Robin (Random) - Group 1"
             values:
              - admin@szukammilionera.pl
              - hello@szukammilionera.pl
              - witaj@szukammilionera.pl
              - admin2@szukammilionera.pl
              - hello2@szukammilionera.pl
              - witaj2@szukammilionera.pl
              - witamy@szukammilionera.pl
              - witamy2@szukammilionera.pl
         - GR2:
             title: "Round Robin (Random) - Group 2"
             values:
               - hello@meskamilosc.pl
               - admin@meskamilosc.pl
     outgoing:
        - admin@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  admin@szukammilionera.pl
            smtp_password:  SM11837
            from:           admin@szukammilionera.pl
        - hello@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello@szukammilionera.pl
            smtp_password:  SM11837
            from:           hello@szukammilionera.pl
        - witaj@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  witaj@szukammilionera.pl
            smtp_password:  SM11837
            from:           witaj@szukammilionera.pl
        - admin2@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  admin2@szukammilionera.pl
            smtp_password:  SM11837
            from:           admin2@szukammilionera.pl
        - hello2@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello2@szukammilionera.pl
            smtp_password:  SM11837
            from:           hello2@szukammilionera.pl
        - witamy@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  witamy@szukammilionera.pl
            smtp_password:  SM11837
            from:           witamy@szukammilionera.pl
        - hello@meskamilosc.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello@meskamilosc.pl
            smtp_password:  MM11837
            from:           hello@meskamilosc.pl
        - admin@meskamilosc.pl:
            mailer:         smtp
            smtp_host:      "smtp.gmail.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  admin@meskamilosc.pl
            smtp_password:  MM11837
            from:           admin@meskamilosc.pl
        # - hello@expatcalling.com:
        #     mailer:         smtp
        #     smtp_host:      "smtp.gmail.com"
        #     smtp_port:      587
        #     smtp_security:  tls
        #     smtp_debug:     0 #integer greather value more debug
        #     smtp_username:  hello@expatcalling.com
        #     smtp_password:  EC11837
        #     from:           hello@expatcalling.com
    links:
      default_login_expire_period:  172800 #in seconds - 2 days
      default_expire_period:        604800 #in seconds - 7 days
      default_lifetime:             1814400 #in seconds - 21 days
    matches:
      max_weight:        21
      nb_desc_quesitons: 18
      use_queue:         no

dev:
  .domains:
      domain_cultures:   #do not have :sf_culture in the routes
          pl:             [pl.pd.dincho.bonex.us, pl.polishdate.bonex.us, mm.polishdate.bonex.us]
          en:             [polishdate.bonex.us, du.polishdate.bonex.us]
      catalog_domains:
          "pd.dincho.bonex.us":           www.polishdate.com
          "polishdate.bonex.us":          www.polishdate.com
          "branch.pd.dincho.bonex.us":    www.polishdate.com
          "pl.polishdate.bonex.us":       www.szukammilionera.com
          "pl.pd.dincho.bonex.us":        www.szukammilionera.com
          "du.polishdate.bonex.us":       www.dyskretnyuklad.com
          "ec.polishdate.bonex.us":       www.expatcalling.com
          "mm.polishdate.bonex.us":       www.meskamilosc.pl
  mail:
    enabled:                yes
    use_queue:              no
    phpmailer_exceptions:   no
    rethrow_exception:      no
    smtp_debug:       5
  matches:
    use_queue:        no
    error_exception:  yes
stag:
  .domains:
      domain_cultures:   #do not have :sf_culture in the routes
          pl:             [pl.polishdate.bonex.us, mm.polishdate.bonex.us]
          en:             [polishdate.bonex.us, du.polishdate.bonex.us]
      catalog_domains:
          "polishdate.bonex.us":          www.polishdate.com
          "pd.dincho.bonex.us":           www.polishdate.com
          "branch.pd.dincho.bonex.us":    www.polishdate.com
          "pl.polishdate.bonex.us":       www.szukammilionera.com
          "pl.pd.dincho.bonex.us":        www.szukammilionera.com
          "du.polishdate.bonex.us":       www.dyskretnyuklad.com
          "ec.polishdate.bonex.us":       www.expatcalling.com
          "mm.polishdate.bonex.us":       www.meskamilosc.pl
  mail:
    enabled:          yes
    use_queue:        yes
  matches:
    use_queue:        yes
prod:
    .domains:
        domain_cultures:   #do not have :sf_culture in the routes
            pl:             [www.szukammilionera.com, www.meskamilosc.pl]
            en:             [www.polishdate.com, www.dyskretnyuklad.com, www.expatcalling.com]
        catalog_domains:    [] #no trasforms
    mail:
      enabled:          yes
      use_queue:        yes
    matches:
      use_queue:        yes
test:
    mail:
      class:            testPrMail
      error_exception:  yes
trans:
