default:
    beta_period:        on
    brand_text:         LoveStreet.pl
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    base_domain:        pd.dincho.bonex.us #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             pl.pd.dincho.bonex.us
    version:            "v1.2.5/HEAD"
    mail:
        host:           imap.gmail.com
        port:           993
        username:       incoming@polishdate.com
        password:       PD11837
        from:           admin@polishdate.com
        mailer:         smtp
        smtp_host:      "sslv2://smtp.gmail.com"
        smtp_port:      465
        smtp_security:  off #security is set via host address socket transport
        smtp_debug:     off
        smtp_username:  admin@polishdate.com
        smtp_password:  PD11837
