all:
    beta_period:        off
    brand_text:         SzukamMilionera.com
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    version:            "v1.7.7"
    sfImageTransformPlugin:
      mime_type:
        auto_detect: true
        library: gd_mime_type # Fileinfo (PECL), MIME_Type (PEAR), gd_mime_type (GD)
      font_dir: %SF_DATA_DIR%/fonts/
    mail:
     class:             prMail
     enabled:           no
     use_queue:         no
     phpmailer_exceptions:   yes
     rethrow_exception:      no
     smtp_debug:        0
     incoming:
        host:           imap.gmail.com
        port:           993
        username:       incoming@polishdate.com
        password:       PD11837
     rr_groups: #the values should match the outgoing keys below
         - GR1:
             title: "Round Robin (Random) - Group 1"
             values:
              - mandrill
         - GR2:
             title: "Round Robin (Random) - Group 2"
             values:
              - mandrill
     outgoing:
        - mandrill:
            mailer:         smtp
            smtp_host:      "smtp.mandrillapp.com"
            smtp_port:      587
            smtp_security:  tls
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  polishdate@gmail.com
            smtp_password:  64Ga3K8alLDa-w6mSGVl6w
            from:           polishdate@gmail.com
    links:
      default_login_expire_period:  172800 #in seconds - 2 days
      default_expire_period:        604800 #in seconds - 7 days
      default_lifetime:             1814400 #in seconds - 21 days
    matches:
      max_weight:        21
      nb_desc_quesitons: 18
      use_queue:         no
    .domains:
      domain_cultures:
        pl: []
        en: []
      catalog_domains:  []

dev:
  .domains:
      domain_cultures:   #do not have :sf_culture in the routes
          pl:             [szukammilionera.localhost, pl.pd.dincho.bonex.us, pl.polishdate.bonex.us, mm.polishdate.bonex.us]
          en:             [polishdate.localhost, polishdate.bonex.us, du.polishdate.bonex.us, cs.polishdate.bonex.us, db.polishdate.bonex.us]
      catalog_domains:
          "polishdate.localhost":         www.polishdate.com
          "polishdate.bonex.us":          www.polishdate.com
          "branch.pd.dincho.bonex.us":    www.polishdate.com
          "szukammilionera.localhost":    www.szukammilionera.com
          "pl.polishdate.bonex.us":       www.szukammilionera.com
          "pl.pd.dincho.bonex.us":        www.szukammilionera.com
          "du.polishdate.bonex.us":       www.dyskretnyuklad.com
          "ec.polishdate.bonex.us":       www.expatcalling.com
          "mm.polishdate.bonex.us":       www.meskamilosc.pl
          "cs.polishdate.bonex.us":       www.cafesayang.com
          "cafesayang.localhost":         www.cafesayang.com
          "db.polishdate.bonex.us":       www.datingbistro.com
          "datingbistro.localhost":       www.datingbistro.com
  mail:
    enabled:                yes
    use_queue:              no
    phpmailer_exceptions:   no
    rethrow_exception:      no
    smtp_debug:       5
  matches:
    use_queue:        no
    error_exception:  yes
stag:
  .domains:
      domain_cultures:   #do not have :sf_culture in the routes
          pl:             [pl.polishdate.bonex.us, mm.polishdate.bonex.us]
          en:             [polishdate.bonex.us, du.polishdate.bonex.us, cs.polishdate.bonex.us, db.polishdate.bonex.us]
      catalog_domains:
          "polishdate.bonex.us":          www.polishdate.com
          "pd.dincho.bonex.us":           www.polishdate.com
          "branch.pd.dincho.bonex.us":    www.polishdate.com
          "pl.polishdate.bonex.us":       www.szukammilionera.com
          "pl.pd.dincho.bonex.us":        www.szukammilionera.com
          "du.polishdate.bonex.us":       www.dyskretnyuklad.com
          "ec.polishdate.bonex.us":       www.expatcalling.com
          "mm.polishdate.bonex.us":       www.meskamilosc.pl
          "cs.polishdate.bonex.us":       www.cafesayang.com
          "db.polishdate.bonex.us":       www.datingbistro.com
  mail:
    enabled:          yes
    use_queue:        yes
  matches:
    use_queue:        yes
prod:
    .domains:
        domain_cultures:   #do not have :sf_culture in the routes
            pl:             [www.szukammilionera.com, www.meskamilosc.pl]
            en:             [www.polishdate.com, www.dyskretnyuklad.com, www.expatcalling.com, www.cafesayang.com, www.datingbistro.com]
        catalog_domains:    [] #no trasforms
    mail:
      enabled:          yes
      use_queue:        yes
    matches:
      use_queue:        yes
test:
    mail:
      class:            testPrMail
      error_exception:  yes
trans:
