default:
    beta_period:        off
    brand_text:         SzukamMilionera.com
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    base_domain:        pd.dincho.bonex.us #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             pl.pd.dincho.bonex.us
    version:            "v1.3.9/HEAD"
    mail:
        host:           imap.gmail.com
        port:           993
        username:       incoming@polishdate.com
        password:       PD11837
        from:           main@lovestreet.pl
        mailer:         smtp
        smtp_host:      "sslv2://smtp.gmail.com"
        smtp_port:      465
        smtp_security:  off #security is set via host address socket transport
        smtp_debug:     off
        smtp_username:  main@lovestreet.pl 
        smtp_password:  LS11837
    links:
      default_login_expire_period:  172800 #in seconds - 2 days
      default_expire_period:        604800 #in seconds - 7 days
      default_lifetime:             1814400 #in seconds - 21 days
