all:
    beta_period:        off
    brand_text:         SzukamMilionera.com
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    version:            "v1.6.4"
    mail:
     class:             prMail
     enabled:           no
     use_queue:         no
     error_exception:   no
     smtp_debug:        0
     incoming:
        host:           imap.gmail.com
        port:           993
        username:       incoming@polishdate.com
        password:       PD11837
     outgoing:
        - admin@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  admin@szukammilionera.pl
            smtp_password:  SM11837
            from:           admin@szukammilionera.pl
        - hello@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello@szukammilionera.pl
            smtp_password:  SM11837
            from:           hello@szukammilionera.pl
        - witaj@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  witaj@szukammilionera.pl
            smtp_password:  SM11837
            from:           witaj@szukammilionera.pl
        - admin2@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  admin2@szukammilionera.pl
            smtp_password:  SM11837
            from:           admin2@szukammilionera.pl
        - hello2@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello2@szukammilionera.pl
            smtp_password:  SM11837
            from:           hello2@szukammilionera.pl
        - witaj2@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  witaj2@szukammilionera.pl
            smtp_password:  SM11837
            from:           witaj2@szukammilionera.pl
        - witamy@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  witamy@szukammilionera.pl
            smtp_password:  SM11837
            from:           witamy@szukammilionera.pl
        - witamy2@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  witamy2@szukammilionera.pl
            smtp_password:  SM11837
            from:           witamy2@szukammilionera.pl
        - hello@expatcalling.com:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello@expatcalling.com
            smtp_password:  EC11837
            from:           hello@expatcalling.com
        - hello@meskamilosc.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello@meskamilosc.pl
            smtp_password:  MM11837
            from:           hello@meskamilosc.pl
    links:
      default_login_expire_period:  172800 #in seconds - 2 days
      default_expire_period:        604800 #in seconds - 7 days
      default_lifetime:             1814400 #in seconds - 21 days
    matches:
      max_weight:       21
      use_queue:        no
      error_exception:  no
dev:
  .domains:
      domain_cultures:   #do not have :sf_culture in the routes
          pl:             [pl.polishdate.bonex.us, mm.polishdate.bonex.us]
          en:             [polishdate.bonex.us, du.polishdate.bonex.us]
      catalog_domains:
          "polishdate.bonex.us":          www.polishdate.com
          "pd.dincho.bonex.us":           www.polishdate.com
          "branch.pd.dincho.bonex.us":    www.polishdate.com
          "pl.polishdate.bonex.us":       www.szukammilionera.com
          "pl.pd.dincho.bonex.us":        www.szukammilionera.com
          "du.polishdate.bonex.us":       www.dyskretnyuklad.com
          "ec.polishdate.bonex.us":       www.expatcalling.com
          "mm.polishdate.bonex.us":       www.meskamilosc.pl
  mail:
    enabled:          yes
    use_queue:        no
    error_exception:  yes
    smtp_debug:       5
  matches:
    use_queue:        no
    error_exception:  yes
stag:
  .domains:
      domain_cultures:   #do not have :sf_culture in the routes
          pl:             [pl.polishdate.bonex.us, mm.polishdate.bonex.us]
          en:             [polishdate.bonex.us, du.polishdate.bonex.us]
      catalog_domains:
          "polishdate.bonex.us":          www.polishdate.com
          "pd.dincho.bonex.us":           www.polishdate.com
          "branch.pd.dincho.bonex.us":    www.polishdate.com
          "pl.polishdate.bonex.us":       www.szukammilionera.com
          "pl.pd.dincho.bonex.us":        www.szukammilionera.com
          "du.polishdate.bonex.us":       www.dyskretnyuklad.com
          "ec.polishdate.bonex.us":       www.expatcalling.com
          "mm.polishdate.bonex.us":       www.meskamilosc.pl
    mail:
      enabled:          yes
      use_queue:        yes
    matches:
      use_queue:        yes
prod:
    .domains:
        domain_cultures:   #do not have :sf_culture in the routes
            pl:             [www.szukammilionera.com, www.meskamilosc.pl]
            en:             [www.polishdate.com, www.dyskretnyuklad.com, www.expatcalling.com]
        catalog_domains:    [] #no trasforms
    mail:
      enabled:          yes
      use_queue:        yes
    matches:
      use_queue:        yes
test:
    mail:
      class:            testPrMail
      error_exception:  yes
trans:
