default:
    beta_period:        off
    brand_text:         LoveStreet.pl
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    base_domain:        pd.dincho.bonex.us #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             pl.pd.dincho.bonex.us
    version:            "v1.2.4/HEAD"
    mail:
        host:           imap.gmail.com
        port:           993 #should be 993 on production/test server
        username:       incoming@polishdate.com
        password:       PD11837
        from:           admin@polishdate.com
        mailer:         smtp
        smtp_host:      "ssl://smtp.gmail.com"
        smtp_port:      465
        smtp_username:  admin@polishdate.com
        smtp_password:  PD11837
