all:
    beta_period:        off
    brand_text:         SzukamMilionera.com
    admin_user_salt:    wPIXsALxMa6SPLWnh5dyMQ3J4ERjsmBA
    version:            "v1.5"
    mail:
     enabled:           no
     use_queue:         no
     error_exception:   no
     incoming:
        host:           imap.gmail.com
        port:           993
        username:       incoming@polishdate.com
        password:       PD11837
     outgoing:
        - admin@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  admin@szukammilionera.pl
            smtp_password:  SM11837
            from:           admin@szukammilionera.pl
        - hello@szukammilionera.pl:
            mailer:         smtp
            smtp_host:      "sslv3://smtp.gmail.com"
            smtp_port:      465
            smtp_security:  off #security is set via host address socket transport
            smtp_debug:     0 #integer greather value more debug
            smtp_username:  hello@szukammilionera.pl
            smtp_password:  SM11837
            from:           hello@szukammilionera.pl
    links:
      default_login_expire_period:  172800 #in seconds - 2 days
      default_expire_period:        604800 #in seconds - 7 days
      default_lifetime:             1814400 #in seconds - 21 days
dev:
    base_domain:        pd.dincho.bonex.us #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             pl.pd.dincho.bonex.us
    catalog_domains:    
        "pd.dincho.bonex.us":     www.polishdate.com
        "pl.pd.dincho.bonex.us":  www.szukammilionera.com
        "du.dincho.bonex.us":     www.dyskretnyuklad.com
    mail:
      enabled:          no
      use_queue:        yes
      error_exception:  no
stag:
    base_domain:        pd.dincho.bonex.us #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             pl.pd.dincho.bonex.us
    mail:
      enabled:          yes
      use_queue:        yes
      error_exception:  no
prod:
    base_domain:        www.polishdate.com #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             www.szukammilionera.com
    mail:
      enabled:          yes
      use_queue:        yes
trans:
    base_domain:        pd.dincho.bonex.us #always have :sf_culture in the routes
    domains:            #do not have :sf_culture in the routes
        pl:             pl.pd.dincho.bonex.us
    catalog_domains:    
        "pd.dincho.bonex.us":     www.polishdate.com
        "pl.pd.dincho.bonex.us":  www.szukammilionera.com
        "du.dincho.bonex.us":     www.dyskretnyuklad.com
    mail:
      enabled:          no
      error_exception:  no