default:
    beta_period:   off
    primary_domain: PolishRomance.com
    brand_text:     PolishRomance.com
    mail:
        host:      mail.bonex.us
        port:      993
        username:  autocheck@polishromance.com
        password:  dincho
        from:      admin@PolishRomance.com
        mailer:    smtp
        smtp_host:  72.68.67.18
        #smtp_username:  autocheck@polishromance.com
        #smtp_password:  dincho
