all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          mysql://127.0.0.1/NO_SUCH_DATABASE
      encoding:     utf8

dev:
  propel:
    param:
      dsn:          mysql://pd_dev:polish_dev@127.0.0.1/polishdate_dev
      #dsn:          mysql://pd_stag:polish_stag@127.0.0.1/polishdate_stag
      #dsn:          mysql://pd_prod:polish_prod@127.0.0.1/polishdate_prod

prod:
  propel:
    param:
      dsn:          mysql://pd_dev:polish_dev@127.0.0.1/polishdate_dev
      #dsn:          mysql://pd_prod:polish_prod@127.0.0.1/polishdate_prod

stag:
  propel:
    param:
      dsn:          mysql://pd_stag:polish_stag@127.0.0.1/polishdate_stag

test:
  propel:
    param:
      dsn:          mysql://pd_test:polish_test@127.0.0.1/polishdate_test

trans:
  propel:
    param:
      dsn:          mysql://pd_dev:polish_dev@127.0.0.1/polishdate_dev
      #dsn:          mysql://pd_stag:polish_stag@127.0.0.1/polishdate_stag
      #dsn:          mysql://pd_prod:polish_prod@127.0.0.1/polishdate_prod     