forgotYourPassword:
    is_secure:  off
forgotPasswordInfo:
    is_secure: off
forgotPasswordConfirm:
    is_secure:  off
confirmNewPassword:
    is_secure: off
indexse:
    is_secure: off
index:
    is_secure: off
