forgotYourPassword:
    is_secure:  off
forgotPasswordInfo:
    is_secure: off
confirmNewPassword:
    is_secure: off
indexse:
    is_secure: off
index:
    is_secure: off #check moved to the action because of admin access
undoNewEmail:
    is_secure: off
feed:
    is_secure: off    