indexSuccess:
    javascripts: [profile_desc_map, show_hide_tick, profile_image, gmap_elabel]
    stylesheets: [sec_container_no_padding]
simpleProfileSuccess:
    javascripts: [profile_desc_map, show_hide_tick, profile_image, gmap_elabel]
    stylesheets: [sec_container_no_padding]
publicProfileSuccess:
    javascripts: [profile_desc_map, show_hide_tick, profile_image, gmap_elabel]
    stylesheets: [sec_container_no_padding]    
indexseSuccess:
    layout:      se
    stylesheets: [-*]
    javascripts: [-*]
