indexSuccess:
    javascripts: [profile_desc_map, show_hide_tick, profile_image, balloons/balloon.config.js, balloons/balloon.js, "balloons/yahoo-dom-event.js", messagebar]
    stylesheets: [sec_container_no_padding]
simpleProfileSuccess:
    javascripts: [profile_desc_map, show_hide_tick, profile_image]
    stylesheets: [sec_container_no_padding]
publicProfileSuccess:
    javascripts: [profile_desc_map, show_hide_tick, profile_image]
    stylesheets: [sec_container_no_padding]
unavailableProfileSuccess:
    javascripts: [balloons/balloon.config.js, balloons/balloon.js, "balloons/yahoo-dom-event.js"]
    stylesheets: [sec_container_no_padding]
indexseSuccess:
    layout:      se
    stylesheets: [-*]
    javascripts: [-*]
feedSuccess:
  has_layout: off
  http_metas:
    content-type: text/xml

