default:
  components:
    sidebar:  [system, membersSidebar]
editPhotosSuccess:
    javascripts: [/cropper/cropper.js: { position: last }]
    stylesheets: [/cropper/cropper.css: { position: first } ]
