<?php
// auto-generated by sfPropelCrud
// date: 2008/08/01 09:57:51
?>
<?php

/**
 * descAnswerCrud actions.
 *
 * @package    pr
 * @subpackage descAnswerCrud
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class descAnswerCrudActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('descAnswerCrud', 'list');
  }

  public function executeList()
  {
    $this->desc_answers = DescAnswerPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->desc_answer = DescAnswerPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->desc_answer);
  }

  public function executeCreate()
  {
    $this->desc_answer = new DescAnswer();
    $this->desc_answer->setDescQuestionId($this->getRequestParameter('question_id'));
    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->desc_answer = DescAnswerPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->desc_answer);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $desc_answer = new DescAnswer();
    }
    else
    {
      $desc_answer = DescAnswerPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($desc_answer);
    }

    $desc_answer->setId($this->getRequestParameter('id'));
    $desc_answer->setDescQuestionId($this->getRequestParameter('desc_question_id') ? $this->getRequestParameter('desc_question_id') : null);
    $desc_answer->setTitle($this->getRequestParameter('title'));
    $desc_answer->setSearchTitle($this->getRequestParameter('search_title'));

    $desc_answer->save();

    return $this->redirect('descAnswerCrud/show?id='.$desc_answer->getId());
  }

  public function executeDelete()
  {
    $desc_answer = DescAnswerPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($desc_answer);

    $desc_answer->delete();

    return $this->redirect('descAnswerCrud/list');
  }
}
