indexSuccess:
  javascripts:    [messages]
sentSuccess:
  javascripts:    [messages]
sendSuccess:
  javascripts:    [send_message_handlers]
threadSuccess:
  javascripts:    [messages, send_message_handlers]
draftsSuccess:
  javascripts:    [messages]
