<?php
// auto-generated by sfPropelCrud
// date: 2008/09/16 16:07:10
?>
<?php use_helper('Object') ?>

<?php echo form_tag('notificationsCRUD/update') ?>

<?php echo object_input_hidden_tag($notification, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($notification, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Send from:</th>
  <td><?php echo object_input_tag($notification, 'getSendFrom', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Send to:</th>
  <td><?php echo object_input_tag($notification, 'getSendTo', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Reply to:</th>
  <td><?php echo object_input_tag($notification, 'getReplyTo', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Bcc:</th>
  <td><?php echo object_input_tag($notification, 'getBcc', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Subject:</th>
  <td><?php echo object_input_tag($notification, 'getSubject', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Body:</th>
  <td><?php echo object_textarea_tag($notification, 'getBody', array (
  'size' => '70x20',
)) ?></td>
</tr>
<tr>
  <th>Is active*:</th>
  <td><?php echo object_checkbox_tag($notification, 'getIsActive', array (
)) ?></td>
</tr>
<tr>
  <th>To admins*:</th>
  <td><?php echo object_checkbox_tag($notification, 'getToAdmins', array (
)) ?></td>
</tr>
<tr>
  <th>Days:</th>
  <td><?php echo object_input_tag($notification, 'getDays', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Whn:</th>
  <td><?php echo object_input_tag($notification, 'getWhn', array (
  'size' => 20,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($notification->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'notificationsCRUD/delete?id='.$notification->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'notificationsCRUD/list') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'notificationsCRUD/list') ?>
<?php endif; ?>
</form>
