<?php
// auto-generated by sfPropelCrud
// date: 2008/09/16 16:07:10
?>
<h1>notificationsCRUD</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Send from</th>
  <th>Send to</th>
  <th>Reply to</th>
  <th>Bcc</th>
  <th>Subject</th>
  <th>Is active</th>
  <th>To admins</th>
  <th>Days</th>
  <th>Whn</th>
</tr>
</thead>
<tbody>
<?php foreach ($notifications as $notification): ?>
<tr>
    <td><?php echo $notification->getId() ?></td>
      <td><?php echo link_to($notification->getName(), 'notificationsCRUD/edit?id='.$notification->getId()) ?></td>
      <td><?php echo $notification->getSendFrom() ?></td>
      <td><?php echo $notification->getSendTo() ?></td>
      <td><?php echo $notification->getReplyTo() ?></td>
      <td><?php echo $notification->getBcc() ?></td>
      <td><?php echo $notification->getSubject() ?></td>
      <td><?php echo $notification->getIsActive() ?></td>
      <td><?php echo $notification->getToAdmins() ?></td>
      <td><?php echo $notification->getDays() ?></td>
      <td><?php echo $notification->getWhn() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'notificationsCRUD/create') ?>
