<?php
// auto-generated by sfPropelCrud
// date: 2008/09/16 16:07:10
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $notification->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $notification->getName() ?></td>
</tr>
<tr>
<th>Send from: </th>
<td><?php echo $notification->getSendFrom() ?></td>
</tr>
<tr>
<th>Send to: </th>
<td><?php echo $notification->getSendTo() ?></td>
</tr>
<tr>
<th>Reply to: </th>
<td><?php echo $notification->getReplyTo() ?></td>
</tr>
<tr>
<th>Bcc: </th>
<td><?php echo $notification->getBcc() ?></td>
</tr>
<tr>
<th>Trigger name: </th>
<td><?php echo $notification->getTriggerName() ?></td>
</tr>
<tr>
<th>Subject: </th>
<td><?php echo $notification->getSubject() ?></td>
</tr>
<tr>
<th>Body: </th>
<td><?php echo $notification->getBody() ?></td>
</tr>
<tr>
<th>Is active: </th>
<td><?php echo $notification->getIsActive() ?></td>
</tr>
<tr>
<th>To admins: </th>
<td><?php echo $notification->getToAdmins() ?></td>
</tr>
<tr>
<th>Days: </th>
<td><?php echo $notification->getDays() ?></td>
</tr>
<tr>
<th>Whn: </th>
<td><?php echo $notification->getWhn() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'notificationsCRUD/edit?id='.$notification->getId()) ?>
&nbsp;<?php echo link_to('list', 'notificationsCRUD/list') ?>
