<?php
// auto-generated by sfPropelCrud
// date: 2008/12/23 13:27:40
?>
<?php

/**
 * msgCollection actions.
 *
 * @package    PolishRomance
 * @subpackage msgCollection
 * @author     Dincho Todorov <dincho
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class msgCollectionActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('msgCollection', 'list');
  }

  public function executeList()
  {
    $this->msg_collections = MsgCollectionPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->msg_collection = MsgCollectionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->msg_collection);
  }

  public function executeCreate()
  {
    $this->msg_collection = new MsgCollection();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->msg_collection = MsgCollectionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->msg_collection);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $msg_collection = new MsgCollection();
    }
    else
    {
      $msg_collection = MsgCollectionPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($msg_collection);
    }

    $msg_collection->setId($this->getRequestParameter('id'));
    $msg_collection->setTransCollectionId($this->getRequestParameter('trans_collection_id') ? $this->getRequestParameter('trans_collection_id') : null);
    $msg_collection->setName($this->getRequestParameter('name'));

    $msg_collection->save();

    return $this->redirect('msgCollection/list');
  }

  public function executeDelete()
  {
    $msg_collection = MsgCollectionPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($msg_collection);

    $msg_collection->delete();

    return $this->redirect('msgCollection/list');
  }
}
