<?php
// auto-generated by sfPropelCrud
// date: 2008/07/17 15:31:12
?>
<?php

/**
 * staticPagesCrud actions.
 *
 * @package    pr
 * @subpackage staticPagesCrud
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class staticPagesCrudActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('staticPagesCrud', 'list');
  }

  public function executeList()
  {
    $this->static_pages = StaticPagePeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->static_page = StaticPagePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->static_page);
  }

  public function executeCreate()
  {
    $this->static_page = new StaticPage();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->static_page = StaticPagePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->static_page);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $static_page = new StaticPage();
    }
    else
    {
      $static_page = StaticPagePeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($static_page);
    }

    $static_page->setId($this->getRequestParameter('id'));
    $static_page->setSlug($this->getRequestParameter('slug'));
    $static_page->setCulture('en');
    $static_page->setTitle($this->getRequestParameter('title'));

    $static_page->save();

    return $this->redirect('staticPagesCrud/show?id='.$static_page->getId());
  }

  public function executeDelete()
  {
    $static_page = StaticPagePeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($static_page);

    $static_page->delete();

    return $this->redirect('staticPagesCrud/list');
  }
}
