searchEngine:
  is_secure: off
index:
  is_secure: off
page:
  is_secure: off
message:
  is_secure: off
tellFriend:
  is_secure: off
tellFriendConfirm:
  is_secure: off
emails:
  is_secure: off
blockedUser:
  is_secure: off
