emailsSuccess:
  stylesheets: [  ]
searchEngineSuccess:
  layout:      se
  stylesheets: [-*]
  javascripts: [-*]
flagSuccess:
  javascripts: [flag_profile_handlers]
reportBugSuccess:
  javascripts: [flash_detect]
